[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node --experimental-specifier-resolution=node server/index.js"
healthcheckPath = "/test"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
